r"""
MHD-turbulence contribution to the GW spectrum from a cosmological
first-order phase transition.

Based on:

A. Roper Pol, C. Caprini, A. Neronov, and D. Semikoz,
"Gravitational wave signal from primordial magnetic fields in the
Pulsar Timing Array frequency band",
Phys.Rev.D 105 (2022) 12; [arXiv:2201.05630 [astro-ph.CO]].

Also see: A. Kosowsky, A. Mack and T. Kahniashvili, "Gravitational
radiation from cosmological turbulence", Phys.Rev.D 66 (2002) 024030;
[arXiv:astro-ph/0111483] and C. Caprini, R. Durrer and G. Servant, "The
stochastic gravitational wave background from turbulence and magnetic
fields generated by a first-order phase transition", JCAP 12 (2009)
024; [arXiv:0909.0622 [astro-ph.CO]] (foundational MHD-turbulence GW
spectrum derivations).
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, ClassVar, TypeAlias

import jax
import jax.numpy as jnp
import jax.typing as jtp

from gwb_templates.FOPT_templates.pt_base import (
    a_hubble,
    double_broken_power_law,
    jac_double_broken_power_law_amp_freqs,
    redshift_omega,
)
from gwb_templates.template import AnalyticTemplate

ArrayLike: TypeAlias = jtp.ArrayLike


class PtTurbulence(AnalyticTemplate):
    r"""
    MHD-turbulence GW spectrum from a cosmological FOPT.

    Free parameters
    ---------------
    log_Omega_s
        :math:`\log_{10}` of the fractional energy density in the
        turbulent source.
    log_R_H_star
        :math:`\log_{10}` of the bubble size times the Hubble rate.
    log_T_star
        :math:`\log_{10}` of the transition temperature in GeV.

    Configuration
    -------------
    amplitude_prefactor
        Numerical factor in the amplitude. Defaults to
        `PtTurbulence.DEFAULT_AMPLITUDE_PREFACTOR`.
    spectral_index_low_f
        Low-frequency spectral index. Defaults to
        `PtTurbulence.DEFAULT_SPECTRAL_EXPONENTS[0]`.
    spectral_index_mid_f
        Intermediate-frequency spectral index. Defaults to
        `PtTurbulence.DEFAULT_SPECTRAL_EXPONENTS[1]`.
    spectral_index_high_f
        High-frequency spectral index. Defaults to
        `PtTurbulence.DEFAULT_SPECTRAL_EXPONENTS[2]`.
    transition_smoothness_low_f
        Smoothness of the transition between the low and intermediate frequency
        spectral slopes. Defaults to `PtTurbulence.DEFAULT_SPECTRAL_EXPONENTS[3]`.
    transition_smoothness_high_f
        Smoothness of the transition between the intermediate and high frequency
        spectral slopes. Defaults to `PtTurbulence.DEFAULT_SPECTRAL_EXPONENTS[4]`.
    """

    #: Default spectral amplitude prefactor (Roper Pol et al. 2022).
    DEFAULT_AMPLITUDE_PREFACTOR: ClassVar[float] = 0.085
    #: Eddy-turnover scaling N_eddy.
    N_EDDY: ClassVar[float] = 2.0
    #: Default values for fixed spectral exponents (n_1, n_2, n_3, a_1, a_2).
    DEFAULT_SPECTRAL_EXPONENTS: ClassVar[tuple[float, float, float, float, float]] = (
        3.0,
        1.0,
        -8.0,
        4.0,
        2.15,
    )

    bibtex_entries: ClassVar[tuple[str, ...]] = (
        r"""
@article{Caprini:2024hue,
    author = "Caprini, Chiara and Jinno, Ryusuke and Lewicki, Marek and Madge, Eric
        and Merchand, Marco and Nardini, Germano and Pieroni, Mauro and Roper Pol,
        Alberto and Vaskonen, Ville",
    collaboration = "LISA Cosmology Working Group",
    title = "{Gravitational waves from first-order phase transitions in LISA:
        reconstruction pipeline and physics interpretation}",
    eprint = "2403.03723",
    archivePrefix = "arXiv",
    primaryClass = "astro-ph.CO",
    reportNumber = "LISA-COSWG-24-01, CERN-TH-2024-029",
    doi = "10.1088/1475-7516/2024/10/020",
    journal = "JCAP",
    volume = "10",
    pages = "020",
    year = "2024"
}
""",
        r"""
@article{RoperPol:2022iel,
    author = "Roper Pol, Alberto and Caprini, Chiara and Neronov, Andrii and Semikoz,
        Dmitri",
    title = "{Gravitational wave signal from primordial magnetic fields in the Pulsar
        Timing Array frequency band}",
    eprint = "2201.05630",
    archivePrefix = "arXiv",
    primaryClass = "astro-ph.CO",
    doi = "10.1103/PhysRevD.105.123502",
    journal = "Phys. Rev. D",
    volume = "105",
    number = "12",
    pages = "123502",
    year = "2022"
}
""",
        r"""
@article{Kosowsky:2001xp,
    author = "Kosowsky, Arthur and Mack, Andrew and Kahniashvili, Tinatin",
    title = "{Gravitational radiation from cosmological turbulence}",
    eprint = "astro-ph/0111483",
    archivePrefix = "arXiv",
    reportNumber = "RAP-334",
    doi = "10.1103/PhysRevD.66.024030",
    journal = "Phys. Rev. D",
    volume = "66",
    pages = "024030",
    year = "2002"
}
""",
        r"""
@article{Caprini:2009yp,
    author = "Caprini, Chiara and Durrer, Ruth and Servant, Geraldine",
    title = "{The stochastic gravitational wave background from turbulence and magnetic
        fields generated by a first-order phase transition}",
    eprint = "0909.0622",
    archivePrefix = "arXiv",
    primaryClass = "astro-ph.CO",
    doi = "10.1088/1475-7516/2009/12/024",
    journal = "JCAP",
    volume = "12",
    pages = "024",
    year = "2009"
}
""",
    )

    def __init__(
        self,
        amplitude_prefactor: float = DEFAULT_AMPLITUDE_PREFACTOR,
        spectral_index_low_f: float = DEFAULT_SPECTRAL_EXPONENTS[0],
        spectral_index_mid_f: float = DEFAULT_SPECTRAL_EXPONENTS[1],
        spectral_index_high_f: float = DEFAULT_SPECTRAL_EXPONENTS[2],
        transition_smoothness_low_f: float = DEFAULT_SPECTRAL_EXPONENTS[3],
        transition_smoothness_high_f: float = DEFAULT_SPECTRAL_EXPONENTS[4],
        *,
        model_name: str | None = None,
        model_label: str | None = None,
        parameter_labels: Mapping[str, str] | None = None,
        prior_by_param: Mapping[str, Any] | None = None,
    ) -> None:
        self.amplitude_prefactor: float = float(amplitude_prefactor)
        self.spectral_exponents: tuple[float, float, float, float, float] = (
            float(spectral_index_low_f),
            float(spectral_index_mid_f),
            float(spectral_index_high_f),
            float(transition_smoothness_low_f),
            float(transition_smoothness_high_f),
        )

        default_labels = {
            "log_Omega_s": r"$\log_{10}\Omega_s$",
            "log_R_H_star": r"$\log_{10}(R_* H_*)$",
            "log_T_star": r"$\log_{10}(T_*/\mathrm{GeV})$",
        }
        default_priors = {
            "log_Omega_s": {"min": -6.0, "max": 0.0},
            "log_R_H_star": {"min": -3.0, "max": 0.0},
            "log_T_star": {"min": -2.0, "max": 4.0},
        }

        super().__init__(
            model_name=model_name,
            model_label=(
                model_label if model_label is not None else "PT MHD Turbulence"
            ),
            parameter_labels=(
                parameter_labels if parameter_labels is not None else default_labels
            ),
            prior_by_param=(
                prior_by_param if prior_by_param is not None else default_priors
            ),
        )

    def omega_gw_h2(
        self,
        frequency: ArrayLike,
        log_Omega_s: ArrayLike,
        log_R_H_star: ArrayLike,
        log_T_star: ArrayLike,
    ) -> jax.Array:
        r"""Evaluate the MHD-turbulence FOPT spectrum at ``frequency``."""
        Omega_s = 10.0**log_Omega_s
        R_H_star = 10.0**log_R_H_star
        T_star = 10.0**log_T_star

        # Alfven speed
        vA = jnp.sqrt(0.75 * Omega_s)

        aH_star = a_hubble(T_star)
        h2FGW0 = redshift_omega(T_star)

        f_1 = vA / self.N_EDDY * aH_star / R_H_star
        f_2 = 2.2 * aH_star / R_H_star
        r_f = f_2 / f_1  # = 2.2 * N_eddy / vA

        n_1, n_2, n_3, a_1, a_2 = self.spectral_exponents
        norm = r_f**3 * (1.0 + r_f**a_1) ** (-2.0 / a_1) * 2.0 ** (-11.0 / 3.0 / a_2)
        prefactor = (
            3.0 * self.amplitude_prefactor * norm / (4.0 * jnp.pi**2 * self.N_EDDY)
        )
        h2Omega2 = h2FGW0 * prefactor * vA * Omega_s**2 * R_H_star**2

        return double_broken_power_law(
            frequency,
            jnp.log10(h2Omega2),
            jnp.log10(f_1),
            jnp.log10(f_2),
            n_1,
            n_2,
            n_3,
            a_1,
            a_2,
        )

    def _grad_theta_omega_gw_h2_analytical(
        self,
        frequency: jax.Array,
        theta: jax.Array,
    ) -> jax.Array:
        r"""
        Analytic Jacobian of the MHD-turbulence FOPT spectrum w.r.t.
        ``(log_Omega_s, log_R_H_star, log_T_star)``.

        Uses the chain rule through :func:`double_broken_power_law`.  The
        :math:`g_*` tables are piecewise-constant, so their T-derivatives
        vanish almost everywhere (consistent with autodiff through
        :func:`jnp.select`).
        """
        log_Omega_s, log_R_H_star, log_T_star = theta[0], theta[1], theta[2]

        Omega_s = 10.0**log_Omega_s
        R_H_star = 10.0**log_R_H_star
        T_star = 10.0**log_T_star

        vA = jnp.sqrt(0.75 * Omega_s)
        aH_star = a_hubble(T_star)
        h2FGW0 = redshift_omega(T_star)

        f_1 = vA / self.N_EDDY * aH_star / R_H_star
        f_2 = 2.2 * aH_star / R_H_star
        r_f = f_2 / f_1  # = 2.2 * N_eddy / vA

        n_1, n_2, n_3, a_1, a_2 = self.spectral_exponents
        norm = r_f**3 * (1.0 + r_f**a_1) ** (-2.0 / a_1) * 2.0 ** (-11.0 / 3.0 / a_2)
        prefactor = (
            3.0 * self.amplitude_prefactor * norm / (4.0 * jnp.pi**2 * self.N_EDDY)
        )
        h2Omega2 = h2FGW0 * prefactor * vA * Omega_s**2 * R_H_star**2

        J_inner = jac_double_broken_power_law_amp_freqs(
            frequency,
            jnp.log10(h2Omega2),
            jnp.log10(f_1),
            jnp.log10(f_2),
            n_1,
            n_2,
            n_3,
            a_1,
            a_2,
        )  # shape (..., 3)

        # h2Omega2 ∝ norm(r_f) * vA * Omega_s^2 * R^2,  r_f ∝ Omega_s^{-1/2}
        # d log_h2Omega2/d log_Omega_s = 1 + r_f^{a_1}/(1 + r_f^{a_1})
        # d log_h2Omega2/d log_R_H_star = 2
        # d log_h2Omega2/d log_T_star = 0
        # f_1 ∝ vA * aH_star / R,  vA ∝ Omega_s^{1/2},  aH_star ∝ T
        # f_2 ∝ aH_star / R
        rf_a1 = r_f**a_1
        d_logOmega2_d_logOs = 1.0 + rf_a1 / (1.0 + rf_a1)

        dq_dp = jnp.array(
            [
                [d_logOmega2_d_logOs, 2.0, 0.0],  # log_h2Omega2
                [0.5, -1.0, 1.0],  # log_f_1
                [0.0, -1.0, 1.0],  # log_f_2
            ]
        )

        return J_inner @ dq_dp
